@endpoint = http://localhost:3001

### Request to find all messages
POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query {
  messages {
    content
  }
}

### Request to find message by id
POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query($id: Int!) {
  message(id: $id) {
    id,
    content,
  }
}

{
  "id": 3
}

### Request to find all users
POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query {
  users {
    first_name
  }
}

### Request to find user by id
POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query($id: Int!) {
  user(id: $id) {
    id,
    first_name,
    last_name
  }
}

{
  "id": 3
}

### Request to find all request
POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query {
  requests {
    id,
    message
  }
}

### Request to find a request by id
POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query($id: Int!) {
  request(id: $id) {
    id,
    message
  }
}

{
  "id": 3
}

### Request to find all media
POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query {
  medias {
    id,
    url
  }
}


### Request to find a media by id
POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query Query($id: Int!) {
  media(id: $id) {
    id,
    url
  }
}

{
  "id": 3
}