extend type Mutation{
    # conversation mutations
    createCookieConsents(id: Int!, input: CookieConsentInput!): CookieConsents
    updateCookieConsents(id: Int!, input: CookieConsentInput!): CookieConsents
}