scalar Upload

type Message {
    id: Int!
    content: String!
    user_id: Int!
    conversation_id: Int!
    request_id: Int!
    created_at: String!
    media: [Media]
}

input NewMessageInput {
    content: String! @length(max: 500)
    user_id: Int!
    conversation_id: Int!
    media: [Upload]
}

input UpdateViewedMessage {
    id: [Int!]
}


