type Message {
    id: Int!
    content: String!
    user_id: Int!
    conversation_id: Int!
    created_at: String!
}

input NewMessageInput {
    content: String!
    sender: Int!
    receiver: Int!
    conversationId: Int!
}


