type Mutation {
# User mutations
    createUser(input: CreateUserInput!): User
    createProUser(input: CreateProUserInput!): User
    updateUser(id: Int!, input: UpdateUserInput!): User
    deleteUser(id: Int!): Boolean
}
