### this is what i can get back and how
type Query {
    users: [User!]!
    user: User!
    requests: [Request!]!
    request(id: Int!): Request!
    conversations: [Conversation!]!
    conversation(id: Int!): Conversation!
    messages: [Message!]!
    message(id: Int!): Message! 
    medias: [Media!]!
    media(id: Int!): Media!
}