type Request {
    id: Int!
    urgent: Boolean!
    title: String!
    message: String!
    localization: String!
    user_id: Int!
    category: Category!
}

input CreateRequestInput {
    urgent: Boolean!
    title: String!
    message: String!
    localization: String!
    user_id: Int!
    category: String!
    jobs: String!
}