directive @length(max: Int!) on INPUT_FIELD_DEFINITION
scalar Upload

type Request {
    id: Int!
    urgent: Boolean!
    title: String!
    message: String!
    localization: String!
    range: Int!
    user_id: Int!
    job_id: Int!
}

input Coordinates {
  lng: Float!
  lat: Float!
}

input CreateRequestInput {
    urgent: Boolean!
    title: String! @length(max: 255)
    message: String!
    localization: Coordinates!
    range: Int!
    user_id: Int!
    job_id: Int!
    media: [MediaInput!]
}