type Subscription {
    messageAdded(conversation_ids: [Int!], request_ids: [Int], is_request: Boolean ): [Message!]
    requestAdded(job_ids: [Int!], user_id: Int!): [Request]
    logout(user_id: Int!): LogoutSubscription
    #requestDeleted: Request
}

type LogoutSubscription {
    id: Int!
    value: Boolean!
    multiple: Boolean!
    session: String
}

type UserSubscription {
    id: Int!
    user_id: Int!
    subscriber: String!
    subscriber_id: [Int!]
    created_at: String!
}

input SubscriptionInput {
    user_id: Int!
    subscriber: String!
    subscriber_id: [Int!]
}