extend type Mutation {
  # UserHasHiddenClientRequest mutations
  userHasNotViewedRequest(input: UserHasNotViewedRequestInput!): Boolean
  deleteNotViewedRequest(input: UserHasNotViewedRequestInput!): Boolean
  
}