
type User {
    id: Int!
    first_name: String
    last_name: String
    email: String!
    adress: String
    postal_code: String
    city: String
    siret: String
    denomination: String
    messages: [Message]
}


type AuthPayload {
    token: String!
    refreshToken: String!
}


type AccessToken {
    token: String!
}

input loginInput {
    email: String!
    password: String!
}

input CreateUserInput {
    email: validateEmail!
    password: validatePassword!
}

input ConfirmRegisterEmailInput {
    token: String!
}

input CreateProUserInput {
    email: validateEmail!
    password: validatePassword!
    siret: validateSiret!
}

input UpdateUserInput {
    first_name: String
    last_name: String
    email: validateEmail
    adress: String
    postal_code: validatePostalCode
    city: String
    company_name: String
    siret: validateSiret
}

input ForgotPasswordInput {
    email: String!
}

input ChangePasswordInput {
    oldPassword: validatePassword!
    newPassword: validatePassword!
}

